name: flower_shop
description: Цветочный магазин на Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.2

  shared_preferences: ^2.3.3

  lottie: ^3.1.2

  flutter_form_builder: ^9.3.0

  get: ^4.6.6
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flowerLogo2.png
